apiVersion: apps/v1
kind: Deployment
metadata:
  name: crashloop
  namespace: demo-apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crashloop
  template:
    metadata:
      labels:
        app: crashloop
    spec:
      containers:
      - name: crashloop
        image: busybox
        command: ["sh", "-c", "exit 1"]
